# -*- coding: utf-8 -*-
"""iris-flower-classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/kabeer09/cdd38c298d98ec46f31906c8f74dd8a0/iris-flower-classification.ipynb
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

df = pd.read_csv("/content/archive (4) (2).zip")
df

df.columns

df.shape

df.describe()

df.info()

df.hist()

sns.pairplot(df,hue= 'Species' , size=2).add_legend()

df.corr()

x=df.iloc[:,[1,2,3,4]]
y=df.iloc[:,5]

x.head()

y.head()

from sklearn import preprocessing

lb=preprocessing.LabelEncoder()

df['Species'] = lb.fit_transform(df['Species'])
df['Species']

df.dtypes

y.unique()

x_train,y_train,x_test,y_test =  train_test_split(x,y,test_size=0.2)

x_train.shape

x_test.shape

x_train = x_train[:-1]

from sklearn.neighbors import KNeighborsClassifier

Knn = KNeighborsClassifier(n_neighbors=5)

import numpy as np
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load the iris dataset
iris = load_iris()

# Create a KNN classifier
knn = KNeighborsClassifier(n_neighbors=5)

# Fit the classifier to the entire dataset
knn.fit(iris.data, iris.target)

# Predict the labels of the entire dataset
y_pred = knn.predict(iris.data)

# Evaluate the accuracy of the classifier
accuracy = accuracy_score(iris.target, y_pred)

print("Accuracy:", accuracy)













